// <auto-generated />
using System;
using ArizaTakip.DataAccess.Concrete.EntitiyFrameworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArizaTakip.DataAccess.Migrations
{
    [DbContext(typeof(ArizaTakipContext))]
    [Migration("20201015171347_HataGiderme")]
    partial class HataGiderme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArizaTakip.Entites.Concrete.Ariza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArizaAciklama")
                        .HasColumnType("ntext");

                    b.Property<DateTime>("ArizaOlusturulmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArizaTanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ariza");
                });

            modelBuilder.Entity("ArizaTakip.Entites.Concrete.Cevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArizaId")
                        .HasColumnType("int");

                    b.Property<string>("CevapAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cevap");
                });

            modelBuilder.Entity("ArizaTakip.Entites.Concrete.Cihaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CihazAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CihazKayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CihazTip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cihaz");
                });

            modelBuilder.Entity("ArizaTakip.Entites.Concrete.CihazOzellik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COzellikDeger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COzellikTanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CihazId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CihazOzellik");
                });
#pragma warning restore 612, 618
        }
    }
}
